title: <p align="center"> Le Khanh Duy </p>

logo: "/images/avatar.png?raw=true"

description:
  <p align="center">
  <a href="pdf/CV.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/duy-l%C3%AA-kh%C3%A1nh-393a12210/">LinkedIn</a> |
  <a href="https://github.com/duyvt6663">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursing BS degree in Computer Science at Ho Chi Minh City University of Technology.
  <br><br>
  I am looking for AI Research positions, preferably with a focus on NLP and Deep Learning research.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
