title: <p align="center"> Le Khanh Duy </p>

logo: "/images/avatar.png?raw=true"

description:
  <p align="center">
  <a href="pdf/CV.pdf"><img src="images/resume-icon.png" alt="Resume Icon" style="vertical-align:middle; margin-right:5px; height:1em;">Resume</a> |
  <a href="https://www.linkedin.com/in/duy-l%C3%AA-kh%C3%A1nh-393a12210/"><img src="https://upload.wikimedia.org/wikipedia/commons/f/f8/LinkedIn_icon_circle.svg" alt="Resume Icon" style="vertical-align:middle; margin-right:5px; height:1em;">LinkedIn</a> |
  <a href="https://github.com/duyvt6663"><img src="images/github-logo.png" alt="Github Icon" style="vertical-align:middle; margin-right:5px; height:1em;">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursing BS degree in Computer Science at Ho Chi Minh City University of Technology.
  <br><br>
  I was a recent Research Intern at KAIST Interaction Lab, where I had a publication on Large Language Models in Human-AI Interaction.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
